using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi;
using TSD.Host;
using TSD.Infrastructure;
using ApiModule = TSD.Api.Module;
using InfrastructureModule = TSD.Infrastructure.Module;

var builder = WebApplication.CreateBuilder(args);

// Register Controllers from the TSD.Api assembly
builder.Services.AddControllers()
    .AddApplicationPart(ApiModule.GetAssembly());

// Register MediatR (Scan the Domain project for Handlers)
builder.Services.AddMediatR(cfg =>
    cfg.RegisterServicesFromAssembly(ApiModule.GetDomainAssembly()));

// Register EF Core with SQLite
builder.Services.AddDbContext<MainContext>(options =>
    options.UseSqlite("Data Source=Database\\TSD_Database.db"));

// Register Repositories
InfrastructureModule.RegisterServices(builder.Services);

// Register Global Exception Handling and Problem Details
builder.Services.AddExceptionHandler<GlobalExceptionHandler>();
builder.Services.AddProblemDetails(); // Adds standard RFC 7807 support

// Register mappers
builder.Services.AddAutoMapper(config =>
{
    config.AddMaps(
        ApiModule.GetAssembly(),
        ApiModule.GetDomainAssembly());
});

builder.Services.AddOpenApi();

builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new OpenApiInfo
    {
        Version = "v1",
        Title = "The Springfield Dungeon",
        Description = "An API I've made to play and learn"
    });

    // Build the path to the XML file generated by the project
    var xmlFile = $"{System.Reflection.Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);

    // Tell Swagger to use those XML comments
    options.IncludeXmlComments(xmlPath);
});

var app = builder.Build();

// Global Exception Handling Middleware
app.UseExceptionHandler();

// Simple DB Auto-Creation for Dev
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<MainContext>();
    await db.Database.MigrateAsync();
}

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
    app.UseSwagger();
    app.UseSwaggerUI(options =>
    {
        // This tells the UI where to find the JSON file
        options.SwaggerEndpoint("/swagger/v1/swagger.json", "v1");
        // Sets Swagger at the root (e.g., https://localhost:5001/)
        options.RoutePrefix = "swagger";
    });
    app.UseDeveloperExceptionPage();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();